# Based on https://github.com/Microsoft/GSL

language: cpp
sudo: false
notifications:
  email: true

# Use Linux unless specified otherwise
os: linux
dist: trusty
ruby: 2.3

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps

matrix:
  include:
    # GCC on Linux
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gfortran
            - libgfortran
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    # Clang on Linux
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - gfortran
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    # GCC on OSX
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew update || brew install gcc6 && CC=gcc-6 && CXX=g++-6"

    # Clang on OSX
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
    - eval "${MATRIX_EVAL}"

install:
  # Dependencies required by the CI are installed in ${TRAVIS_BUILD_DIR}/deps/
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}"
  - cd "${DEPS_DIR}"

  # Travis machines have 2 cores
  - JOBS=2

  # Install OpenBLAS
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      BLAS_URL="https://github.com/xianyi/OpenBLAS/archive/v0.3.3.zip"
      mkdir -p OpenBLAS/install  
      cd OpenBLAS
      travis_retry wget ${BLAS_URL} 
      unzip -q -o v0.3.3.zip
      cd OpenBLAS-0.3.3 && make > /dev/null 2>&1
      make install 
    else
      brew update
      brew install homebrew/core/openblas || brew link --overwrite gcc
    fi
   
  # Have CMake to generate build files
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  
script:
  # Build and run tests
  - cmake --build . --config $BUILD_TYPE -- -j${JOBS}
  - ctest -C $BUILD_TYPE --output-on-failure -j${JOBS}

